### ISSUE TITLE
Does not work on devnet with @solana/wallet-adapter-glow

### ISSUE THREAD

**Issue by sethgirvan** [glow-xyz/glow-js#67]
I have not been able to successfully call `signTransaction` on a `Transaction` with glow on devnet (set network to "devnet", have devnet sol), whereas it seems to work fine on mainnet. On devnet some transactions cause the wallet to display the error message "Glow detected an issue with the requested transaction.", while others display the error "You don't have enough SOL for this transaction." with no option to then sign the transaction.

Transactions performed internally with the wallet like sending SPL tokens do still work on devnet.

This is with Glow 0.40.0 extension installed on Chromium 103.0.5060.134.

**Comment by vpontis** [comment]
Can you share some code? Are you passing Devnet to the adapter via JS?

**Comment by sethgirvan** [comment]
Do you mean setting the network via the `_config?: GlowWalletAdapterConfig` argument of the `GlowWalletAdapter` constructor? I actually wasn't doing that since I assumed setting the network in the wallet itself would be enough, but I can give that a try.

**Comment by vpontis** [comment]
The dapp sets the network, not the wallet. This is a conscious security decision

**Comment by sethgirvan** [comment]
Got it. Yeah passing that into the constructor like
```
new GlowWalletAdapter({
  network: WalletAdapterNetwork.Devnet,
})
```
fixes things. Thanks for the quick help!

**Comment by vpontis** [comment]
👍 thanks for opening this, let me know if there's anything else we can help with!
