### ISSUE TITLE
Packages declare exact versions of dependencies, leading to duplicates

### ISSUE THREAD

**Issue by jordaaash** [glow-xyz/glow-js#68]
https://github.com/glow-xyz/glow-js/blob/aa62c4bdb1d606f17c2458a0cda7a9258f523b51/packages/solana-client/package.json#L27-L42

To take an especially gnarly example, `@solana/web3.js` is typically already used by dapps. Declaring it with an exact version as a dependency in this SDK is effectively guaranteed to cause two versions of it to land in the dapp's bundle, which causes various problems (like instanceof check failures) and huge builds.

I think if this code is running in a wallet, sure, lock down the deps. But if it's running in a dapp, leave that up to dapps. Many users won't even realize they have two of these things in their bundles, and the kind of errors you get from it at runtime are terrible to debug unless you know this.

**Comment by vpontis** [comment]
Fixed thank you @jordansexton !
