### ISSUE TITLE
glow/solana client version mismatch

### ISSUE THREAD

**Issue by jordaaash** [glow-xyz/glow-js#80]
`@glow-xyz/glow-client` depends on the pinned version
https://github.com/glow-xyz/glow-js/blob/4c0c2dc2ef8e4bc25b4779b5e4bf066542688eeb/packages/glow-client/package.json#L20

but `@glow-xyz/solana-client` is a higher minor version
https://github.com/glow-xyz/glow-js/blob/4c0c2dc2ef8e4bc25b4779b5e4bf066542688eeb/packages/solana-client/package.json#L3

Additionally, in both cases, the `luxon` dependency is
https://github.com/glow-xyz/glow-js/blob/4c0c2dc2ef8e4bc25b4779b5e4bf066542688eeb/packages/glow-client/package.json#L24

But the `@types/luxon` dependency is a different pinned version
https://github.com/glow-xyz/glow-js/blob/4c0c2dc2ef8e4bc25b4779b5e4bf066542688eeb/packages/glow-client/package.json#L31

Additionally, glow-client depends on a pinned version of web3.js
https://github.com/glow-xyz/glow-js/blob/4c0c2dc2ef8e4bc25b4779b5e4bf066542688eeb/packages/glow-client/package.json#L29

Whereas solana-client uses a looser version
https://github.com/glow-xyz/glow-js/blob/4c0c2dc2ef8e4bc25b4779b5e4bf066542688eeb/packages/solana-client/package.json#L31

This will result in two different versions of web3.js, incompatible types, etc.

Versions of all dependencies should probably be synced across these packages.

**Comment by vpontis** [comment]
@jordansexton I believe this is fixed now, lmk if you have an example where it's still broken for you. Thanks for opening this!

**Comment by jordaaash** [comment]
ty, will test!
