### ISSUE TITLE
window.glow.disconnect is not a function

### ISSUE THREAD

**Issue by jordaaash** [glow-xyz/glow-js#95]
https://github.com/glow-xyz/glow-js/blob/8e14b9e9e950fa2af7337f174a47bb332a149403/packages/glow-client/src/window-types.ts#L77

Glow's types say it has `window.glow.disconnect` event. If you call it from the console:

```
> window.glow.disconnect()

VM14227:1 Uncaught TypeError: window.glow.disconnect is not a function
```

This causes an error for the standard wallet wrapper around Glow, because it expects to be able to call this method:

https://github.com/glow-xyz/glow-js/blob/8e14b9e9e950fa2af7337f174a47bb332a149403/packages/wallet-standard/src/wallet.ts#L75-L78

If Glow doesn't have this method, we can remove that feature from the standard wrapper, and optionally fix the type declaration.

**Comment by vpontis** [comment]
Oh interesting, yea it should be `signOut` but I can also alias `disconnect` to `signOut`.

**Comment by jordaaash** [comment]
I guess the real question is, do you want dapps routinely, even automatically, calling that function? We could remove it from the standard wrapper (it's an optional API) if that would actually lead to full deauthorizations that the dapp user maybe didn't intend.

**Comment by vpontis** [comment]
> I guess the real question is, do you want dapps routinely, even automatically, calling that function? We could remove it from the standard wrapper (it's an optional API) if that would actually lead to full deauthorizations that the dapp user maybe didn't intend.

I'm ok w/ them calling that function. If an app logs a user out, then the user will be logged out. I think that's ok. 

I added `window.glow.disconnect` and it'll be out in the next release. So closing this now.
